/**
 * Strategy Versioning System - Core Types
 * 
 * Defines interfaces for strategy implementations and profiles
 */

import { Candle } from '../types';
import { TradeSignal } from '../types';

/**
 * Context passed to strategy execution
 */
export interface StrategyContext {
  symbol: string;
  timeframe: string;
  candles: Candle[];
  // Market data service for fetching additional candles
  marketDataService?: any; // MarketDataService type
  // Additional context can be added here
  [key: string]: any;
}

/**
 * Order generated by strategy
 */
export interface StrategyOrder {
  signal: TradeSignal;
  // Additional order metadata
  metadata?: Record<string, any>;
}

/**
 * Result returned by strategy execution
 */
export interface StrategyResult {
  orders: StrategyOrder[];
  debug?: Record<string, any>;
  // Additional result metadata
  metadata?: Record<string, any>;
}

/**
 * Base interface for all strategy implementations
 * 
 * IMPORTANT: Once a strategy implementation is frozen (e.g., GodSmcStrategy),
 * it should NEVER be modified. All future changes must create new implementations.
 */
export interface IStrategy {
  /**
   * Unique key identifying this strategy implementation
   * (e.g., "GOD_SMC_V1", "SMC_V2")
   */
  readonly key: string;

  /**
   * Human-readable display name
   */
  readonly displayName: string;

  /**
   * Execute the strategy and return potential orders
   * 
   * @param context Strategy execution context
   * @returns Strategy result with orders (if any)
   */
  execute(context: StrategyContext): Promise<StrategyResult>;
}

